Feat/mawqit for tv take the tv language as the app language by default
mawaqit/android-tv-app pull request #1018
Opened 2024-02-08 00:22 UTC by YassinNouh21

---

📝 **Summary**
---
This PR introduces a key feature aimed at enhancing user experience by automatically setting the Mawaqit TV app's default language to match the TV's current language setting. 

**This PR is for issue:** #984 

**Description**
---
Leveraging the TV's language setting as the app's default language, we reduce the friction new users might face and cater to a global audience with minimal effort required from the user's end.

Key changes include:

- Automatic detection of the TV's current language setting during the app's initial setup phase.
- Dynamic adjustment of the app's language setting to align with the TV's language, ensuring immediate familiarity and ease of use for the user.
- Thoughtful handling of scenarios where the TV's language is not supported by the app, defaulting to English while providing users the option to choose their preferred language manually.

**Tests**
---
🧪 **Use case 1: Language is available in the app's localization**
---

![image](https://drive.google.com/uc?export=view&id=1ulyhDg_Ac_47KSczOdzv1iGFJ92ADEA2)

---
🧪 **Use case 2: Language is not available in the app's localization**
---

![image3](https://drive.google.com/uc?export=view&id=1xAJIV_sV0PnaFVdnF0rOuEagNLzubCk4)

---
🧪 **Use case 3: Exception handling during data fetching**
--- 

![image2](https://drive.google.com/uc?export=view&id=1zj1KGmHWXsSZa3fR_ibAidfzAcLVA4Vm)

---
**Checklist:**
---
- [x] **Coding Standards:** I have reviewed my code to ensure it follows the project's coding standards.
- [x] **Testing:** I have thoroughly tested the changes across the described use cases and confirmed they work as expected.
- [x] **Merge Conflicts:** I have resolved any merge conflicts with the latest main/development branch.
- [x] **Branch Status:** The branch is up-to-date with the target branch (main/development).

---

2024-02-08 09:26 UTC, ibrahim-zehhaf-mawaqit commented on pubspec.yaml
> +  share_plus: ^7.2.2
to revert

2024-02-08 12:43 UTC, ghassenbenzahra123 commented on lib/src/domain/usecase/on_boarding_usecase.dart
> +    return deviceInfoModel;
directly  ```return await deviceInfoRepository.getAllDeviceInfo();```

2024-02-08 13:12 UTC, ghassenbenzahra123 commented on pubspec.yaml
> -  wakelock: ^0.6.2
to revert also please

2024-02-08 13:56 UTC, ghassenbenzahra123 requested changes
Good work Yassin! some minor updates.

2024-02-09 21:06 UTC, ghassenbenzahra123 approved these changes
LGTM! good work Yassin

2024-02-09 21:58 UTC, merged

2024-02-11 09:36 UTC, ibrahim-zehhaf-mawaqit commented
I tested the issue, please keep the language screen in the on boarding, just select the default language, don't remove the screen