Hotfix/Call status Api
mawaqit/android-tv-app pull request #1093
Opened 2024-04-02 15:25 UTC by ghassenbenzahra123

- This PR removes the android.hadware.usb feature check since its available on smartphones

2024-04-02 22:21 UTC, YassinNouh21 requested changes

2024-04-02 22:21 UTC, YassinNouh21 commented on lib/src/data/data_source/device_info_data_source.dart
> +      print('hasFeature: $hasFeature $feature');
use `logger.d` instead of direct print

2024-04-03 16:04 UTC, ghassenbenzahra123 commented on lib/src/data/data_source/device_info_data_source.dart
> +      print('hasFeature: $hasFeature $feature');
Done

2024-04-03 19:32 UTC, YassinNouh21 approved these changes
LGTM

2024-04-03 19:53 UTC, merged