952 gray screen when jumua is disabled
mawaqit/android-tv-app pull request #959
Opened 2023-12-03 12:35 UTC by YassinNouh21

📝 **Summary**
---
**This PR fixes**  #952

**Description**
---
Resolved an issue where not filling both Juma values and disabling 'Juma as Duhr' resulted in a null exception on Android TV, causing a grey screen. The solution ensures proper handling of null values for Juma times.

**Tests**
---
🧪 **Test Case 1: Juma 1 is null, Juma 2 is not null**
- Description: Validate that the application correctly handles scenarios where Juma 1 is not provided but Juma 2 is.
- Result: 

https://github.com/mawaqit/android-tv-app/assets/70436855/c82f4510-f302-4002-9e88-efd8c4b5b1f0

🧪 **Test Case 2: Juma 1 is not null, Juma 2 is null**
- Description: Ensure that the application operates correctly when Juma 1 is provided, but Juma 2 is not.
- Result: 

https://github.com/mawaqit/android-tv-app/assets/70436855/d2b98db0-aa42-49a3-8bdb-51a6c73997d5

🧪 **Test Case 3: Juma as Duhr**
- Description: Test the functionality when 'Juma as Duhr' is enabled.
- Result: 
- 
https://github.com/mawaqit/android-tv-app/assets/70436855/5bb47eb8-2672-4151-9636-4a8c1d00bafd

🧪 **Test Case 4: Both Juma 1 and Juma 2 are null**
- Description: Check application behavior when both Juma 1 and Juma 2 are not provided.
- Result: 

https://github.com/mawaqit/android-tv-app/assets/70436855/40d7d8dc-80bd-4008-b716-74af3b0f6c67

**Checklist:**
---
- [x] **Coding Standards:** I have reviewed my code to ensure it follows the project's coding standards.
- [x] **Testing:** I have tested the changes and they work as expected.
- [x] **Merge Conflicts:** I have resolved any merge conflicts with the latest main/development branch.
- [x] **Branch Status:** The branch is up-to-date with the target branch (main/development).

2023-12-04 17:17 UTC, ghassenbenzahra123 requested changes
Great work Yassin ! :ok_hand:  All test cases work as intended. 
Just a minor code quality suggestion to improve readability.

2023-12-04 17:17 UTC, ghassenbenzahra123 commented on lib/src/services/mixins/mosque_helpers_mixins.dart
> +    final jumuaaTime = times!.jumua;
you only use jumuaaTime once, you can skip this intermediate variable.

2023-12-04 17:17 UTC, ghassenbenzahra123 commented on lib/src/services/mixins/mosque_helpers_mixins.dart
>    DateTime activeJumuaaDate([DateTime? now]) {
Consider extracting the condition checks into a separate method, this can improve readability.
My suggestion : 
```Dart
DateTime activeJumuaaDate([DateTime? now]) {
  final nextFriday = nextFridayDate(now);

  if (times!.jumuaAsDuhr == true) {
    return timesOfDay(nextFriday)[1].toTimeOfDay()!.toDate(nextFriday);
  }

  if (isJumuaOrJumua2EmptyOrNull()) {
    return nextFriday;
  }

  return times!.jumua!.toTimeOfDay()!.toDate(nextFriday);
}

bool isJumuaOrJumua2EmptyOrNull() {
  return (times?.jumua ?? '').isEmpty && (times?.jumua2 ?? '').isEmpty;
}

2023-12-05 12:00 UTC, YassinNouh21 commented on lib/src/services/mixins/mosque_helpers_mixins.dart
>    DateTime activeJumuaaDate([DateTime? now]) {
GREAT 👍

2023-12-05 12:25 UTC, YassinNouh21 commented on lib/src/services/mixins/mosque_helpers_mixins.dart
>    DateTime activeJumuaaDate([DateTime? now]) {
Done 
I created new private method to handle this logic

2023-12-05 12:27 UTC, YassinNouh21 commented on lib/src/services/mixins/mosque_helpers_mixins.dart
> +    final jumuaaTime = times!.jumua;
I intended to do that so I can split the logic for readability 
-  `final jumuaaTime = times!.jumua` this is for return jumuaa1 time
- `return jumuaaTime!.toTimeOfDay()!.toDate(nextFriday);` this is for parsing the value of juma to time of day and then to date

2023-12-05 12:27 UTC, YassinNouh21 commented on lib/src/services/mixins/mosque_helpers_mixins.dart
> +    final jumuaaTime = times!.jumua;
I also added comments in the codebase for this

2023-12-05 12:33 UTC, ghassenbenzahra123 approved these changes

2023-12-05 13:19 UTC, merged